import { StyleProp, TextStyle } from 'react-native';

export enum UseResponsiveEnum {
  'icon_add-restaurant',
  'icon_alert',
  'icon_area',
  'icon_angle-down',
  'icon_angle-left',
  'icon_angle-right',
  'icon_angle-up',
  'icon_bell',
  'icon_bookmark',
  'icon_bookmark-f',
  'icon_building',
  'icon_camera',
  'icon_cart',
  'icon_cash',
  'icon_city',
  'icon_clock',
  'icon_comment',
  'icon_credit',
  'icon_cross',
  'icon_delivery',
  'icon_disconnect',
  'icon_discount',
  'icon_dish',
  'icon_edit',
  'icon_empty-bag',
  'icon_failed',
  'icon_filter',
  'icon_delino',
  'icon_gallery',
  'icon_gps',
  'icon_guid',
  'icon_headset',
  'icon_home',
  'icon_info',
  'icon_lock',
  'icon_bag',
  'icon_settings',
  'icon_popup',
  'icon_mail',
  'icon_map',
  'icon_megaphone',
  'icon_minus',
  'icon_mobile',
  'icon_more',
  'icon_note',
  'icon_online',
  'icon_orders',
  'icon_packaging',
  'icon_pickup',
  'icon_pin',
  'icon_plus',
  'icon_pos',
  'icon_refresh',
  'icon_restaurant',
  'icon_search',
  'icon_stop',
  'icon_stopwatch',
  'icon_tag',
  'icon_telephone',
  'icon_terms',
  'icon_tick',
  'icon_trash',
  'icon_user',
  'icon_facebook',
  'icon_gplus',
  'icon_instagram',
  'icon_linkedin',
  'icon_telegram',
  'icon_twitter',
  'icon_addtobasket',
  'icon_menu',
  'icon_logout',
  'icon_maximize',
  'icon_arrow-left',
  'icon_arrow-right',
  'icon_share',
  'icon_group',
  'icon_disconnect-f',
  'icon_zoom',
  'icon_calendar',
  'icon_aparat',
  'icon_envelope-f',
  'icon_alert-f',
  'icon_coupon',
  'icon_copy',
  'icon_note-f',
  'icon_building-f',
  'icon_home-f',
  'icon_earth',
  'icon_compass-f',
  'icon_flag',
  'icon_grid-f',
  'icon_list-f',
  'icon_credit-card',
  'icon_payment-method',
  'icon_new',
  'icon_cross-circle',
  'icon_helmet',
  'icon_most-ordered',
  'icon_sort',
  'icon_heart',
  'icon_heart-f',
  'icon_compass',
  'icon_sub-category',
  'icon_star',
  'icon_star-f',
  'icon_star-half',
  'icon_pin-f',
  'icon_arrow-circle-left',
  'icon_arrow-circle-right',
  'icon_whatsapp',
  'icon_wallet-in',
  'icon_wallet-out',
  'icon_dashboard',
  'icon_rest-menu',
}

export interface IIconProps {
  style?: StyleProp<TextStyle>;
  name: keyof typeof UseResponsiveEnum;
  size: number;
  color: string;
  svg?: boolean;
  boxed?: boolean;
  boxColor?: string;
  boxSize?: number;
}
